name: itch.io upload

on:
  push:
    branches: [ "main" ]
    paths:
      - "version"
      - ".github/workflows/godot-to-itch.yml.yml"
      - "export_presets.html.example"
  workflow_dispatch:

env:
  WORKING_DIRECTORY: .

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir html5

      - name: Create export_presets.cfg
        run: cp export_presets.html.example export_presets.cfg


      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1
        with:
          godot-version: 4.3
          working-directory: ${{ env.WORKING_DIRECTORY }} 


      - name: itch.io butler upload
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: henrikp
          game: massive-destruction
          channel: html5
          working-directory: html5


